steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/simpleappnodemysql/simpleappnodemysql'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/simpleappnodemysql/simpleappnodemysql'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'simpleappnodemysql'
      - '--image'
      - 'gcr.io/simpleappnodemysql/simpleappnodemysql'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# Specify the service account to use
serviceAccount: 'simplenodejs@simpleappnodemysql.iam.gserviceaccount.com'

# Specify a logs bucket to store build logs
logsBucket: 'gs://simplenodebucket'

options:
  logging: CLOUD_LOGGING_ONLY


timeout: 1200s